kind: pipeline
name: default

steps:
- name: prepare
  image: google/dart:2.2.0
#  volumes:
#  - name: pub-cache
#    path: /opt/flutter/.pub-cache
  commands:
  - pub get
  - ls
  - ls ~ -a
  - cd /
  - ls -a
  - cd $DART_SDK
  - ls -a

- name: analyze
  image: google/dart:2.2.0
  commands:
  - dartanalyzer .

- name: publish-check
  image: google/dart:2.2.0
  commands:
  - pub publish --dry-run

- name: publish
  image: plugins/docker
  settings:
    repo: v7lin/simple_pub_server
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    tags:
#    - ${DRONE_TAG}
    - latest
#  when:
#    event:
#    - tag

volumes:
- name: pub-cache
  temp: {}