kind: pipeline
name: default

steps:
- name: prepare
  image: google/dart:2.2.0
  volumes:
  - name: pub-cache
    path: /root/.pub-cache
  commands:
  - pub get

- name: analyze
  image: google/dart:2.2.0
  volumes:
  - name: pub-cache
    path: /root/.pub-cache
  commands:
  - dartanalyzer .

- name: publish-check
  image: google/dart:2.2.0
  volumes:
  - name: pub-cache
    path: /root/.pub-cache
  commands:
  - pub publish --dry-run

- name: publish
  image: plugins/docker
  settings:
    repo: v7lin/simple_pub_server
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    tags:
#    - ${DRONE_TAG}
    - latest
#  when:
#    event:
#    - tag

volumes:
- name: pub-cache
  temp: {}