# 版本
version: "3.7"

# 服务
services:

  pub_server:
    container_name: pub_server
    image: v7lin/simple_pub_server
    restart: always
    ports:
      - 80:8080
    volumes:
      - ../dev-ops-repo/pub_server:/tmp/package-db
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
      - PUB_SERVER_REPOSITORY_DATA=/tmp/package-db
