# 版本
version: "3.7"

# 服务
services:

  simple_pub_server:
    container_name: simple_pub_server
    image: simple_pub_server
    restart: always
    ports:
      - 8080:8080
      - 8181:8181
    volumes:
      - ../dev-ops-repo/simple_pub_server:/tmp/package-db
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
      - PUB_SERVER_REPOSITORY_DATA=/tmp/package-db
